version: '2.0'

services:
  personal-website:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/package.json:/app/package.json
    ports:
      - 8080:8080