version: '3.8'

services:

  app:
    container_name: app
    build:
      context: ../app
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
    env_file:
      - ./.env
    ports:
      - 3000:3000